from selenium.webdriver.common.by import By


BTN_LOGIN_REGISTER = (By.XPATH, "//button[contains(text(), 'Вход и регистрация') or contains(text(), 'Войти')]")
BTN_NO_ACCOUNT = (By.XPATH, "//button[contains(text(), 'Нет аккаунта')] | //a[contains(text(), 'Нет аккаунта')]")
BTN_CREATE_ACCOUNT = (By.XPATH, "//button[contains(text(), 'Создать аккаунт') or contains(text(), 'Зарегистрироваться')]")
BTN_SUBMIT_LOGIN = (By.XPATH, "//button[contains(text(), 'Войти')]")
BTN_LOGOUT = (By.XPATH, "//button[contains(text(), 'Выйти')]")
BTN_CREATE_AD = (By.XPATH, "//*[contains(text(), 'Разместить объявление')]")
BTN_PUBLISH = (By.XPATH, "//button[contains(text(), 'Опубликовать')]")
INPUT_EMAIL = (By.NAME, "email")
INPUT_PASSWORD = (By.NAME, "password")
INPUT_PASSWORD_CONFIRM = (By.NAME, "submitPassword") 
INPUT_TITLE = (By.XPATH, "//input[@placeholder='Название']") 
INPUT_DESCRIPTION = (By.XPATH, "//*[@placeholder='Описание товара']")
INPUT_PRICE = (By.XPATH, "//input[@placeholder='Стоимость']")
SELECT_CATEGORY = (By.NAME, "category")
SELECT_CITY = (By.NAME, "city")
LOCATOR_NEW = (By.XPATH, "//img[@alt='Тестовый товар4']")
USER_AVATAR_BLOCK = (By.CSS_SELECTOR, ".user-profile, .avatar, img[alt='avatar'], div[class*='user']")
USER_NAME_LABEL = (By.XPATH, "//*[contains(text(), 'User.')]")
MODAL_AUTH_TITLE = (By.XPATH, "//*[contains(text(), 'Чтобы разместить объявление, авторизуйтесь')]")
ERROR_MESSAGE_EMAIL = (By.XPATH, "//*[contains(text(), 'Ошибка')]")